

export const TRANSACTION_TYPES = {
  PLAYER_ADDED: 'PLAYER_ADDED',
  FIELD_GAIN: 'FIELD_GAIN',
  FIELD_LOSS: 'FIELD_LOSS',
  PLAYER_TRANSFER: 'PLAYER_TRANSFER',
  PLAYER_ELIMINATED: 'PLAYER_ELIMINATED'
};